# Generated by Django 3.2.9 on 2021-11-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Faculty', models.CharField(max_length=30)),
                ('Group', models.CharField(max_length=255)),
                ('Course', models.IntegerField()),
                ('Date', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
    ]
